include ~/.cache/wal/colors-kitty.conf

### FONTS###

# Defining font style
font_family CaskaydiaCove Nerd Font

# Defining font size
font_size 15

# Avoid conflict
force_ltr no

### STYLE ###

disable_ligatures never

window_padding_width 10

background_opacity 0.5

default_pointer_shape beam

cursor_shape block

shell_integration no-cursor

### MOUSE BEHAVIOR ###

# To click on links
mouse_map ctrl+left release grabbed,ungrabbed mouse_handle_click link

# To click the link under the mouse or move the cursor even when grabbed
mouse_map shift+left click grabbed,ungrabbed mouse_handle_click selection link prompt

# To discard event
mouse_map ctrl+left press grabbed discard_event

# To paste text
mouse_map middle release ungrabbed paste_from_selection

# To select text
mouse_map left press ungrabbed mouse_selection normal

# To select a word
mouse_map left doublepress ungrabbed mouse_selection word

# To select a line
mouse_map left triplepress ungrabbed mouse_selection line

# To extend the selection
mouse_map shift+right press ungrabbed mouse_selection extend

# To select a line from point
mouse_map ctrl+alt+left triplepress ungrabbed mouse_selection line_from_point

# To copy selection
mouse_map right press ungrabbed copy_or_noop

### KEYBOARD BEHAVIOUR ###

# To extend the current selection even when grabbed


### PERFORMANCE ###

# To sync frames with monitor
sync_to_monitor	yes

### SOUNDS ###

# Terminal bell
enable_audio_bell yes

# Will show a flash on screen when bell sounds
visual_bell_duration 0.0

# Will select a color for visual bell
visual_bell_color none

# Will request windows attention
window_alert_on_bell yes

# Bell on tab to sinalize a bell
bell_on_tab "🔔 "

# Will run a command when bell occurs
command_on_bell none

# Path to bell sound
bell_path none

# Will play a sound theme of kitty
linux_bell_theme __custom
